
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RALC
 */
public class Principal extends javax.swing.JFrame {
    public String universo;
    public Universo main = new Universo();
    public int ser_seleccionado;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.universo = "";
        ser_seleccionado = 0;
        this.setExtendedState(MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.BLACK);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Crear_Seres_Vivos = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_nombre_raza = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sp_ki = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        sp_max_anios = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        tf_nombre_planeta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Modificar = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nombre_raza1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sp_ki1 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        sp_max_anios1 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        tf_nombre_planeta1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Seres_Vivos = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_seres_vivos = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        Menu_pop = new javax.swing.JPopupMenu();
        mp_modificar = new javax.swing.JMenuItem();
        mp_eliminar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jm_crear_seres_vivos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jm_seres_vivos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jm_guardar_archivo = new javax.swing.JMenuItem();

        Crear_Seres_Vivos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seres Vivos");
        Crear_Seres_Vivos.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre Raza");
        Crear_Seres_Vivos.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));
        Crear_Seres_Vivos.getContentPane().add(tf_nombre_raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 117, 193, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ki");
        Crear_Seres_Vivos.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        sp_ki.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 10));
        Crear_Seres_Vivos.getContentPane().add(sp_ki, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 179, 59, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Número Máximo Años");
        Crear_Seres_Vivos.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        sp_max_anios.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 10));
        Crear_Seres_Vivos.getContentPane().add(sp_max_anios, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 268, 59, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre Planeta");
        Crear_Seres_Vivos.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));
        Crear_Seres_Vivos.getContentPane().add(tf_nombre_planeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 348, 164, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Crear_Seres_Vivos.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 408, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/f4.jpg"))); // NOI18N
        Crear_Seres_Vivos.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 520));

        Modificar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Seres Vivos");
        Modificar.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 200, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre Raza");
        Modificar.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 220, 40));
        Modificar.getContentPane().add(tf_nombre_raza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 220, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ki");
        Modificar.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 120, 40));

        sp_ki1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 10));
        Modificar.getContentPane().add(sp_ki1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 70, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Número Máximo Años");
        Modificar.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 290, 40));

        sp_max_anios1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 10));
        Modificar.getContentPane().add(sp_max_anios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 70, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre Planeta");
        Modificar.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 240, 40));
        Modificar.getContentPane().add(tf_nombre_planeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 164, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Modificar.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 408, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/f1.jpg"))); // NOI18N
        Modificar.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 520));

        Seres_Vivos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seres Vivos");
        Seres_Vivos.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jl_seres_vivos.setModel(new DefaultListModel());
        jl_seres_vivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_seres_vivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_seres_vivos);

        Seres_Vivos.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 667, 304));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/f3.jpg"))); // NOI18N
        Seres_Vivos.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 520));

        mp_modificar.setText("Modificar");
        mp_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mp_modificarActionPerformed(evt);
            }
        });
        Menu_pop.add(mp_modificar);

        mp_eliminar.setText("Eliminar");
        mp_eliminar.setActionCommand("Eliminar");
        mp_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mp_eliminarActionPerformed(evt);
            }
        });
        Menu_pop.add(mp_eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mejorEsta.jpg"))); // NOI18N

        jMenu1.setText("Principal");

        jMenu3.setText("Crear");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Universo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jm_crear_seres_vivos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jm_crear_seres_vivos.setText("Seres >Vivos");
        jm_crear_seres_vivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_crear_seres_vivosActionPerformed(evt);
            }
        });
        jMenu3.add(jm_crear_seres_vivos);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator2);

        jm_seres_vivos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jm_seres_vivos.setText("Seres Vivos");
        jm_seres_vivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_seres_vivosActionPerformed(evt);
            }
        });
        jMenu1.add(jm_seres_vivos);
        jMenu1.add(jSeparator1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Abrir Archivo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jm_guardar_archivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jm_guardar_archivo.setText("Guardar Archivo");
        jm_guardar_archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_guardar_archivoActionPerformed(evt);
            }
        });
        jMenu1.add(jm_guardar_archivo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, Short.MAX_VALUE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.universo = JOptionPane.showInputDialog("Ingrese el Nombre del universo");
        this.main = new Universo(universo);
        JOptionPane.showMessageDialog(this, "El universo se ha creado con éxito\n"
                + "No olvide guardarlo después");
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jm_crear_seres_vivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_crear_seres_vivosActionPerformed
        // TODO add your handling code here:
        if (jm_crear_seres_vivos.isEnabled()) {
            System.out.println("dasdads");
        }
        this.Crear_Seres_Vivos.setModal(true);
        Crear_Seres_Vivos.pack();
        Crear_Seres_Vivos.setLocationRelativeTo(this);
        Crear_Seres_Vivos.setVisible(true);
        
    }//GEN-LAST:event_jm_crear_seres_vivosActionPerformed

    private void jm_guardar_archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_guardar_archivoActionPerformed
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro 
                = new FileNameExtensionFilter("Archivos de Texto", "txt");
        jfc.addChoosableFileFilter(filtro);
        int x = main.getNombre().length();
       
        if ((main.getNombre()).substring(x-5,x-1).equals(".txt")) {
            jfc.setSelectedFile(new File(main.getNombre()+".txt"));
        }else{
            jfc.setSelectedFile(new File(main.getNombre()));
        }
        
        int seleccion = jfc.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            main.setArchivo(jfc.getSelectedFile());
            try {
                main.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Se ha guardado con éxito");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "¡Ups! Ocurrió un error");
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    
        /*try {
            // TODO add your handling code here:
            this.main.escribirArchivo();
            JOptionPane.showMessageDialog(this, "El Universo se ha guardado con éxito");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,"¡Ups! No se guardado el universo");
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jm_guardar_archivoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        try {
            JFileChooser jfc = new JFileChooser();
            //filtros__texto(que se desea que aparzca en el conbox en el filtro y luego separador por copa, las extexnsiones)
            FileNameExtensionFilter filtro
                    = new FileNameExtensionFilter("Archivo de Textos", "txt");
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);
            //evaluamos la selecion, si dentro del filechooser presiono ok
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();//aqui me devuelve todo el arcivo; aqui me hace una refernacia no juna instanciascion
                main.setArchivo(fichero);
                
            }
            
            //setFileFiltre o addChooserbor (Uno lo deja establecidopor defecto y el otro lo agrega a laa cola de filtro que ya existe)
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
        }
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String raza, planeta;
        int ki, anios;
        raza = this.tf_nombre_raza.getText();
        planeta = this.tf_nombre_planeta.getText();
        ki = Integer.parseInt(this.sp_ki.getValue()+"");
        anios = Integer.parseInt(this.sp_max_anios.getValue()+"");
        main.getSeres_vivos().add(new Seres_Vivos(raza, ki, anios, planeta));
        JOptionPane.showMessageDialog(Crear_Seres_Vivos, "El Ser Vivo ha sido creado con éxito");
        this.tf_nombre_raza.setText("");
        this.tf_nombre_planeta.setText("");
        this.sp_ki.setValue(1);
        this.sp_max_anios.setValue(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jm_seres_vivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_seres_vivosActionPerformed
        // TODO add your handling code here:
       //DefaultListModel modelo = (DefaultListModel) this.jl_seres_vivos.getModel();
       DefaultListModel modelo = new DefaultListModel();
        for (Seres_Vivos s : main.getSeres_vivos()) {
            modelo.addElement(s);
        }
        this.jl_seres_vivos.setModel(modelo);
        
        this.Seres_Vivos.setModal(true);
        Seres_Vivos.pack();
        Seres_Vivos.setLocationRelativeTo(this);
        Seres_Vivos.setVisible(true);
        
        
        
    }//GEN-LAST:event_jm_seres_vivosActionPerformed

    private void jl_seres_vivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_seres_vivosMouseClicked
        // TODO add your handling code here:
        ser_seleccionado = this.jl_seres_vivos.getSelectedIndex();
        if(evt.isMetaDown()){
            
            Menu_pop.show(evt.getComponent(), 
                        evt.getX(), evt.getY()); 
        }
    }//GEN-LAST:event_jl_seres_vivosMouseClicked

    private void mp_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mp_eliminarActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) this.jl_seres_vivos.getModel();
        modelo.removeElementAt(ser_seleccionado);
        this.main.getSeres_vivos().remove(ser_seleccionado);
        JOptionPane.showMessageDialog(Seres_Vivos, "¡MONSTRUO! Has Asesinado a un ser vivo");
    }//GEN-LAST:event_mp_eliminarActionPerformed

    private void mp_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mp_modificarActionPerformed
        // TODO add your handling code here:
        this.tf_nombre_planeta1.setText(main.getSeres_vivos().get(ser_seleccionado).getNombre_planeta());
        this.tf_nombre_raza1.setText(main.getSeres_vivos().get(ser_seleccionado).getNombre_raza());
        this.sp_ki1.setValue(main.getSeres_vivos().get(ser_seleccionado).getKi());
        this.sp_ki1.setValue(main.getSeres_vivos().get(ser_seleccionado).getMax_anios());
        
        this.Modificar.setModal(true);
        Modificar.pack();
        Modificar.setLocationRelativeTo(this);
        Modificar.setVisible(true);
    }//GEN-LAST:event_mp_modificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        main.getSeres_vivos().get(ser_seleccionado).setNombre_planeta(this.tf_nombre_planeta1.getText());
        main.getSeres_vivos().get(ser_seleccionado).setNombre_raza(this.tf_nombre_raza1.getText());
        main.getSeres_vivos().get(ser_seleccionado).setKi(Integer.parseInt(this.sp_ki1.getValue()+""));
        main.getSeres_vivos().get(ser_seleccionado).setMax_anios(Integer.parseInt(this.sp_max_anios1.getValue()+""));
        JOptionPane.showMessageDialog(Modificar, "Se ha modificado con éxito");
        jm_seres_vivosActionPerformed(evt);
        Modificar.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Crear_Seres_Vivos;
    private javax.swing.JPopupMenu Menu_pop;
    private javax.swing.JDialog Modificar;
    private javax.swing.JDialog Seres_Vivos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JList<String> jl_seres_vivos;
    private javax.swing.JMenuItem jm_crear_seres_vivos;
    private javax.swing.JMenuItem jm_guardar_archivo;
    private javax.swing.JMenuItem jm_seres_vivos;
    private javax.swing.JMenuItem mp_eliminar;
    private javax.swing.JMenuItem mp_modificar;
    private javax.swing.JSpinner sp_ki;
    private javax.swing.JSpinner sp_ki1;
    private javax.swing.JSpinner sp_max_anios;
    private javax.swing.JSpinner sp_max_anios1;
    private javax.swing.JTextField tf_nombre_planeta;
    private javax.swing.JTextField tf_nombre_planeta1;
    private javax.swing.JTextField tf_nombre_raza;
    private javax.swing.JTextField tf_nombre_raza1;
    // End of variables declaration//GEN-END:variables
}
